server:
  port: 4004

spring:
  cloud:
    gateway:
      # noinspection SpringBootApplicationYaml
      routes:

        - id: auth-service-route
          uri: http://host.docker.internal:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1


        - id: patient-service-route
          uri: http://host.docker.internal:4009
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        # REST CLIENT -> http://localhost:4004/api-docs/patients
        # API GATEWAY -> http://patient-service:4009/v3/api-docs
        - id: api-docs-patient-route
          uri: http://host.docker.internal:4009
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs


        - id: api-docs-auth-route
          uri: http://host.docker.internal:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs
